blank_issues_enabled: false
contact_links:
  - name: Payara Community Forum
    url: http://www.payara.org/forum
    about: Please ask and answer questions about the Payara Platform here.
  - name: Security Issues
    url: https://mailxto.com/0hwfjr
    about: Write an email to security@payara.fish to report security flaws and related issues.
