name: Abandoned Labeler
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  abandoned-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check for abandoned issues
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pendingLabel = "Pending";
            const abandonedLabel = "Abandoned";
            const timeThreshold = 5 * 60 * 60 * 1000 // 5 Hrs
            //5 * 60 * 1000 // 5 Minute
            // 5 * 24 * 60 * 60 * 1000; // 5 days

            const issuesResponse = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: pendingLabel,
              state: "open",
            });

            for (const issue of issuesResponse.data) {
              const updatedAt = new Date(issue.updated_at).getTime();
              const currentTime = new Date().getTime();

              if (currentTime - updatedAt > timeThreshold) {
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: [abandonedLabel],
                });

                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issue.number,
                  name: pendingLabel,
                });

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: "It's been more than 5 Hours since your last update. Could you please provide an update?",
                });
              }
            }